from __future__ import annotations

import html
from collections import defaultdict
from pathlib import Path
from urllib.parse import quote

from .models import Catalog, RecordStatus, RepositoryRecord
from .settings import Settings


def _escape(value: str | None) -> str:
    return (
        html.escape(value or "—", quote=True)
        .replace("[", "&#91;")
        .replace("]", "&#93;")
        .replace("|", "&#124;")
        .replace("`", "&#96;")
        .replace("\n", " ")
        .replace("\r", " ")
    )


def _repo_slug(repo: RepositoryRecord) -> str:
    return f"{repo.full_name}.md"


def _file_sort_key(source_path: str) -> tuple[int, str]:
    return source_path.count("/"), source_path.lower()


def _file_links(repo: RepositoryRecord, limit: int | None = None) -> str:
    files = sorted(
        (item for item in repo.files if item.status == RecordStatus.ACTIVE),
        key=lambda item: _file_sort_key(item.source_path),
    )
    shown = files if limit is None else files[:limit]
    links = [
        f"[{_escape(item.source_path)}]({item.raw_url}) ([Source]({item.source_url}))"
        for item in shown
    ]
    if limit is not None and len(files) > limit:
        index_path = quote(f"indexes/{_repo_slug(repo)}", safe="/")
        links.append(f"[All {len(files)}]({index_path})")
    return "<br>".join(links)


def _repo_order(repo: RepositoryRecord) -> tuple[float, int, str]:
    return -repo.heat, -repo.stars, repo.full_name.lower()


def _repository_table(repos: list[RepositoryRecord], settings: Settings) -> list[str]:
    lines = [
        "| Repository | Instruction files | Language | Stars | 7d Δ | Last push | Heat | Checked |",
        "|---|---|---:|---:|---:|---:|---:|---:|",
    ]
    for repo in repos:
        repository = f"[{_escape(repo.full_name)}]({repo.html_url})"
        lines.append(
            f"| {repository} | {_file_links(repo, settings.readme_file_limit)} | "
            f"{_escape(repo.language)} | {repo.stars:,} | +{repo.stars_delta_7d:,} | "
            f"{repo.pushed_at.date().isoformat()} | {repo.heat:.1f} | "
            f"{repo.last_checked_at.date().isoformat()} |"
        )
    return lines


def render_readme(catalog: Catalog, settings: Settings) -> str:
    categories = [rule.name for rule in settings.categories] + ["Other"]
    grouped: dict[str, list[RepositoryRecord]] = defaultdict(list)
    for repo in catalog.repositories:
        grouped[repo.category].append(repo)

    lines = [
        "# free-agent-md",
        "",
        "A daily-updated index of public `AGENTS.md`, `CLAUDE.md`, and `GEMINI.md` files.",
        "Snapshots are preserved verbatim for reference; their contents are untrusted and are never executed or rendered by this project.",
        "",
        f"Last run: `{catalog.generated_at.isoformat()}` · Candidates: **{catalog.stats.candidates}** · "
        f"Scanned: **{catalog.stats.repositories_scanned}** · Matches: **{catalog.stats.repositories_matched}** · "
        f"Files: **{catalog.stats.files_found}** · [Archive](ARCHIVE.md)",
        "",
    ]
    for category in categories:
        lines.extend([f"## {category}", ""])
        repos = sorted(grouped.get(category, []), key=_repo_order)
        if not repos:
            lines.extend(["_No repositories in this category._", ""])
            continue
        visible = repos[: settings.readme_category_limit]
        remaining = repos[settings.readme_category_limit :]
        lines.extend(_repository_table(visible, settings))
        lines.append("")
        if remaining:
            lines.extend(
                [
                    "<details>",
                    f"<summary>Show {len(remaining)} more repositories</summary>",
                    "",
                    *_repository_table(remaining, settings),
                    "",
                    "</details>",
                    "",
                ]
            )
    lines.extend(
        [
            "## About the snapshots",
            "",
            "Each entry identifies its upstream repository, SPDX license (or `NOASSERTION` in the machine-readable catalog), "
            "and a source link fixed to the observed commit. See [NOTICE.md](NOTICE.md) for attribution and takedown details.",
            "",
            "The catalog is generated by software. Repository metadata is escaped, and instruction-file contents are never embedded here.",
            "",
            "## Methodology",
            "",
            "Candidates are collected from configurable GitHub star/activity tiers. Only the repository root and configured agent directories "
            "are inspected, without recursive tree scans. Heat combines repository-scale star percentile (50%), "
            "seven-day star-growth percentile (30%), and push recency with a 14-day half-life (20%). "
            "See [`config.yml`](config.yml) for the deterministic category rules and scan limits.",
            "",
            "## Running locally",
            "",
            "```powershell",
            "py -3.12 -m venv .venv",
            ".\\.venv\\Scripts\\python.exe -m pip install -e \".[dev]\"",
            ".\\.venv\\Scripts\\pytest.exe",
            ".\\.venv\\Scripts\\free-agent-md.exe dry-run",
            "```",
            "",
            "Set `GITHUB_TOKEN` for authenticated API limits. Before publishing a fork, set `repository` in `config.yml`; "
            "GitHub Actions automatically uses `GITHUB_REPOSITORY`.",
            "",
        ]
    )
    return "\n".join(lines)


def render_index(repo: RepositoryRecord) -> str:
    lines = [
        f"# {_escape(repo.full_name)} instruction files",
        "",
        f"Upstream: [{_escape(repo.full_name)}]({repo.html_url}) · License: `{_escape(repo.license)}` · "
        f"Commit: `{repo.commit_sha}`",
        "",
        "| Type | Path | Snapshot | Fixed source | SHA-256 | Size |",
        "|---|---|---|---|---|---:|",
    ]
    active_files = [item for item in repo.files if item.status == RecordStatus.ACTIVE]
    for item in sorted(active_files, key=lambda value: _file_sort_key(value.source_path)):
        lines.append(
            f"| `{item.kind.value}` | `{_escape(item.source_path)}` | [Raw]({item.raw_url}) | "
            f"[Source]({item.source_url}) | `{item.sha256}` | {item.size:,} B |"
        )
    lines.append("")
    return "\n".join(lines)


def render_archive(catalog: Catalog) -> str:
    lines = [
        "# Archive",
        "",
        "Snapshots remain available when an upstream repository is archived, an instruction file is removed, or a repository leaves the daily candidate set.",
        "Archived entries do not participate in current rankings.",
        "",
        "| Repository | Status | License | Last checked | Files |",
        "|---|---|---|---:|---:|",
    ]
    for repo in sorted(catalog.archived, key=lambda item: item.full_name.lower()):
        lines.append(
            f"| [{_escape(repo.full_name)}]({repo.html_url}) | `{repo.status.value}` | "
            f"`{_escape(repo.license)}` | {repo.last_checked_at.date().isoformat()} | {len(repo.files)} |"
        )
    if not catalog.archived:
        lines.append("| — | — | — | — | 0 |")
    lines.extend(
        [
            "",
            "## Archived files",
            "",
            "| Repository | Path | Status | Snapshot | Fixed source | Last seen |",
            "|---|---|---|---|---|---:|",
        ]
    )
    archived_files = []
    for repo in catalog.repositories:
        archived_files.extend(
            (repo, item) for item in repo.files if item.status != RecordStatus.ACTIVE
        )
    for repo in catalog.archived:
        archived_files.extend((repo, item) for item in repo.files)
    for repo, item in sorted(
        archived_files,
        key=lambda pair: (pair[0].full_name.lower(), pair[1].source_path.lower()),
    ):
        status = item.status.value if item.status != RecordStatus.ACTIVE else repo.status.value
        lines.append(
            f"| {_escape(repo.full_name)} | `{_escape(item.source_path)}` | `{status}` | "
            f"[Raw]({item.raw_url}) | [Source]({item.source_url}) | "
            f"{item.last_seen_at.date().isoformat()} |"
        )
    if not archived_files:
        lines.append("| — | — | — | — | — | — |")
    lines.append("")
    return "\n".join(lines)


def write_rendered(root: Path, catalog: Catalog, settings: Settings) -> None:
    (root / "indexes").mkdir(parents=True, exist_ok=True)
    (root / "indexes" / ".gitkeep").touch()
    for old_index in (root / "indexes").rglob("*.md"):
        old_index.unlink()
    for repo in catalog.repositories:
        index_path = root / "indexes" / _repo_slug(repo)
        index_path.parent.mkdir(parents=True, exist_ok=True)
        index_path.write_text(render_index(repo), encoding="utf-8")
    (root / "README.md").write_text(render_readme(catalog, settings), encoding="utf-8")
    (root / "ARCHIVE.md").write_text(render_archive(catalog), encoding="utf-8")
